import { start } from './serve.mjs';
import { launch } from './pw.mjs';
const srv = await start(0); const b = await launch();
const page = await (await b.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
const errs = []; page.on('pageerror', (e) => errs.push(String(e.stack || e))); page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await page.goto(srv.url + 'index.html?debug=1');
await page.waitForFunction(() => window.__SM && window.__SM.api, null, { timeout: 120000 });
const api = (f, ...a) => page.evaluate(([f2, a2]) => window.__SM.api[f2](...a2), [f, a]);
const st = await api('start');
await api('settle', st.x + 6, st.z - 6, 0.3);
await api('speed', 3);
await page.waitForFunction(() => window.__SM.api.hall() && window.__SM.api.hall().state === 'active', null, { timeout: 120000 });
const h = await api('hall');
const sp = await api('findSpot', 'house', h.x - 10, h.z + 4, 0.4);
await api('build', 'house', sp[0], sp[1], 0.4);
await new Promise((r) => setTimeout(r, 25000));
await api('cam', h.x, h.z, 22, 0.8, 0.95);
await new Promise((r) => setTimeout(r, 1500));
await page.screenshot({ path: '../.cache/shots/in_ext.png' });
await api('cutaway', 'hall', true);
await new Promise((r) => setTimeout(r, 1200));
await page.screenshot({ path: '../.cache/shots/in_cut.png' });
console.log(JSON.stringify(await api('people')));
console.log('errors', errs.slice(0, 8));
await b.close(); await srv.close();
